rez=['E','b','A','A','d','b','B','E','a','B','a','a','B','B','d','A','c','c','b','e','e','b','a','e','c']
rez_a=rez.count("a")
rez_b=rez.count("b")
rez_c=rez.count("c")
rez_d=rez.count("d")
rez_e=rez.count("e")
razlika_a=rez.count("A")
razlika_b=rez.count("B")
razlika_c=rez.count("C")
razlika_d=rez.count("D")
razlika_e=rez.count("E")
print("rezulata za a igraca: ",rez_a-razlika_a)
print("rezulata za b igraca: ",rez_b-razlika_b)
print("rezulata za c igraca: ",rez_c-razlika_c)
print("rezulata za d igraca: ",rez_d-razlika_d)
print("rezulata za e igraca: ",rez_e-razlika_e)
